#!/bin/sh -e

PKG="diabetto"
USER="user"

DOC_DIR="/home/$USER/MyDocs/.documents"
DESTDIR="$DOC_DIR/$PKG"

if [ ! -d $DESTDIR ]; then
    mkdir $DESTDIR
fi

if [ -x /usr/bin/gtk-update-icon-cache ]; then
  /usr/bin/gtk-update-icon-cache -f /usr/share/icons/hicolor
fi

if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database
fi

if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database /usr/share/mime
fi

exit 0

